### ISSUE TITLE
Make it easier to follow CSL repository requirements

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/csl-validator#10]
Now that we have http://formatter.citationstyles.org/ (https://github.com/citation-style-language/formatter), which reformats styles similar to https://github.com/citation-style-language/utilities/blob/master/csl-reindenting-and-info-reordering.py, and allows validation against the stricter https://github.com/citation-style-language/schema/blob/master/csl-repository.rnc, I'm wondering what the best workflows would be to guide users towards a style submission.

I could keep http://validator.citationstyles.org/ as the landing page. When a user tests a style that doesn't generate validation errors, we currently [provide](http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcitation-style-language%2Fstyles%2Fmaster%2Fapa.csl&version=1.0.1) a link to https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md. We could replace this with a link to a wizard/form that helps the user follow https://github.com/citation-style-language/styles/wiki/Style-Requirements. We can also offer validation results against csl-repository.rnc, and show a textarea box with the reformatted style, and perhaps a download button to save it to disk.

I know @fbennett already played with a way to directly create a GitHub pull request from a webpage, but that seems like a later worry.

**Comment by adam3smith** [comment]
Between offering the repository version for validation, auto-reformatting styles, and providing feedback on PRs, I think we've checked most boxes here.
