### ISSUE TITLE
Change link on github repo page

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/csl-validator#11]
The link here

![link](https://cloud.githubusercontent.com/assets/5199995/17440424/d810e026-5b2c-11e6-8114-f3bbf2f8c611.png)

should go to http://validator.citationstyles.org/ instead of just http://citationstyles.org/.

**Comment by rmzelle** [comment]
Uhh, yeah, that would be better.

For some repos without a clear dedicated website I just point to the CSL website (see e.g. https://github.com/citation-style-language/utilities), but here we should point to the validator as we do with https://github.com/citation-style-language/formatter.

**Comment by rmzelle** [comment]
Done. (and thanks for suggesting!)

**Comment by zuphilip** [comment]
:bow:
