### ISSUE TITLE
Validator does not fail reused macro names

### ISSUE THREAD

**Issue by ocouch** [citation-style-language/csl-validator#16]
Reused macro names pass with flying colours. Testing it out, citeproc-js uses the first definition, but the validator should flag reuse, else this could lead to some head scratching...

![image](https://user-images.githubusercontent.com/43231870/116001089-2ee2ea80-a636-11eb-918e-2868fdaff489.png)

**Comment by adam3smith** [comment]
That's an issue with the schema, not the validation tool. 
We could probably check for duplicate macro names in the schema, but for now we are catching this in the CI suite for the style repository, so this is less urgent
