### ISSUE TITLE
Validation against 1.0.1 fails currently

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/csl-validator#18]
I've just tried validating a style against the 1.0.1 schema, and I'm getting this error: 

> Validation failed: HTTP resource not retrievable. The HTTP status from the remote server was: 404.

**Comment by rmzelle** [comment]
@adam3smith, looks like https://github.com/citation-style-language/csl-validator/commit/58ea2f7df0eb10f2b286456e900c09dc6577da2e broke validation against older schemas. The new directory structure was probably introduced between v1.0.1 and v1.0.2.

`var schemaURL = "https://raw.githubusercontent.com/citation-style-language/schema/v" + version + "/schemas/styles/csl.rnc";`

should probably just lose the `/schemas/styles` so it e.g. points to https://raw.githubusercontent.com/citation-style-language/schema/v1.0.1/csl.rnc instead.

**Comment by adam3smith** [comment]
Weird. I tested with 1.0.1 and as you can see, added specific logic for the repo organization change. I'll take a look

Edit: or so I thought. I put the new structure in for the old schemas  for some reason

**Comment by adam3smith** [comment]
Fixed in https://github.com/citation-style-language/csl-validator/commit/d39683b5aaabd1085657c46bb320dde3a2e72b60
