### ISSUE TITLE
License information is missing

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/csl-validator#5]
Can you say something about the licence for this code?

**Comment by rmzelle** [comment]
Uhm, yeah, I'm rather sloppy when keeping track of code licenses.

For the libraries I use:

Ladda (and Spin): https://github.com/hakimel/Ladda/blob/master/LICENSE (MIT license)
Qurl: https://github.com/ryanburnette/Qurl/blob/master/LICENSE (Apache 2.0)

As for my own code, I'm fine with any permissive license. Maybe MIT makes the most sense (http://choosealicense.com/licenses/mit/)? @adam3smith, any thoughts?

**Comment by adam3smith** [comment]
Sorry, I have nothing. I always default to (A)GPL, but for anything CSL I think something more permissive for closed-sourcing makes sense.

**Comment by rmzelle** [comment]
@dstillman, @cpina, @cparnot, do you have any suggestions for a suitable software license? I would prefer to standardize on a single license for all CSL software, if possible.

This might also be a good occasion to decide on a license for everything in https://github.com/citation-style-language/utilities and at https://github.com/citation-style-language/distribution-updater. AGPL?

**Comment by cparnot** [comment]
I’d like to avoid a “viral” license for any of the stuff I contributed. I’d rather go with MIT or BSD.

On Jan 4, 2015, at 5:53 PM, Rintze M. Zelle notifications@github.com wrote:

> @dstillman, @cpina, @cparnot, do you have any suggestions for a suitable software license? I would prefer to standardize on a single license for all CSL software, if possible.
> 
> This might also be a good occasion to decide on a license for everything in https://github.com/citation-style-language/utilities and at https://github.com/citation-style-language/distribution-updater. AGPL?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Charles Parnot
charles.parnot@gmail.com
http://app.net/cparnot
twitter: @cparnot

Your Lab Notebook, Reinvented.
http://findingsapp.com

**Comment by cpina** [comment]
Like @cparnot : MIT or BSD are the most convenient here.

**Comment by rmzelle** [comment]
Cool. In that case I'll go with the MIT license.

@dstillman, is this license okay for https://github.com/citation-style-language/distribution-updater, or do you prefer AGPL?

**Comment by dstillman** [comment]
> @dstillman, is this license okay for https://github.com/citation-style-language/distribution-updater

Yes, that's fine.
