### ISSUE TITLE
File upload input box persistence

### ISSUE THREAD

**Issue by fbennett** [citation-style-language/csl-validator#8]
This may be what you mentioned earlier, not sure. After uploading a local file to the validator, if you refresh the page in the browser, the selection persists in history (it still says "File Upload"), but the button is replaced with an input field (I guess for the URL). The button should also persist.

**Comment by rmzelle** [comment]
I can't reproduce this. Reloading the page always shows the URL menulist drop-down selection and text box for me.

**Comment by fbennett** [comment]
Oooh. Then I must have broken something over here.

**Comment by fbennett** [comment]
Actually, I can reproduce it here on http://citation-style-language.github.io/csl-validator/ Nothing disappears, but the elements are wrong. Here are the steps:

> 1. Select File Upload
> 2. Click Validate and get the result view
> 3. Click the browser refresh button

Expected result:

> 1. The result view disappears, and either:
>    1. the File Upload selection persists, and the "Browse" button for uploading a file appears next to it with the name of the last file uploaded, _or_
>    2. as above, but with a gloss "no file selected" _or_
>    3. the selection returns to "URL" with an empty text box.

Actual result:

> 1. the File Upload selection persists, and the URL text box appears next to it. It is not possible to perform the indicated action without first selecting URL or Text Field, and then reselecting File Upload.

**Comment by rmzelle** [comment]
Hmz, reloading by pressing enter in the address bar doesn't give the issue, but using the refresh button does (Firefox).

**Comment by rmzelle** [comment]
Step 2 isn't even needed.

**Comment by rmzelle** [comment]
Fixed! See also https://bugzilla.mozilla.org/show_bug.cgi?id=46845#c216.

**Comment by fbennett** [comment]
I had no idea other browsers behaved differently. I should get out more ...
